# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='information',
            name='hotel_code',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='information',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
